const appname = "S&B Desire";
const appversion = "Version 1.0.0";
const credits = "Avinash";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "*******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "bea";
const forgetPass = "Forget Password";
const login = "Log in";
const logout = "Log out";
const signup = "Sign Up";
const createNewAccount = "or, create new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have and account? ";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchAnything = "Search anything ...",
    todayDeal = "Today's Deal",
    flashSale = "Flash sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCategories = "Top Categories",
    womenDress = "Women Dress",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    tShirts = "TShirts",
    girlsDress = "Girls Dresses",
    featuredProduct = "Featured Product",
    featuredCategories = "Featured Categories";
const womenClothing = "Women Clothing",
    menClothingFashion = "Men Clothing & Fashion",
    compAccess = "Computer & Accessories",
    automobile = "Automobile",
    kidtoys = "Kids & Toys",
    sports = "Sports",
    jewelery = "Jelewery",
    cellphone = "CellPhone & Tab",
    furniture = "Furniture";
const video = "Video",
    reviews = "Reviews",
    sellerPolicy = "Seller Policy",
    returnPolicy = "Return Policy",
    supportPolicy = "Support Policy",
    productsYouMayLike = "Products you may like";
const wishlist = "My Wishlist", orders = "My Orders", messages = "Messages";
